ClassBased/ClassBased/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('base/',include('base.urls')),
    path('student/',include('Student.urls')),
    path('list/',include('listview.urls')),
    path('detail/',include('detailview.urls')),
    path('edit/',include('editview.urls')),
]

ClassBased/base/urls.py
from django.urls import path
from . import views
from django.views import View
urlpatterns = [
    path('homefun/',views.homefunc,name='homefun'),
    path('homec/',views.HomeClass.as_view(),name='homec'),
    path('contactfun/',views.contactfunc,name='contactfun'),
    path('contactc/',views.ContactClass.as_view(),name='contcatc'),

]

ClassBased/editview/urls.py
from django.urls import path
from . import views
urlpatterns=[
    path('contact/',views.ContactFormView.as_view(),name='contact'),
    path('thankyou/',views.ThankYouView.as_view(),name='thankyou'),
    path('',views.PersonListView.as_view(),name='list'),
    path('create/',views.PersonCreateView.as_view(),name='create'),
    path('det/<int:pk>/',views.PersonDetailView.as_view(),name='detail'),
    path('update/<int:pk>/',views.PersonUpdateView.as_view(),name='update'),
    path('delete/<int:pk>/',views.PersonDeleteView.as_view(),name='delete'),
]

ClassBased/editview/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Person(models.Model):
    name=models.CharField(max_length=70)
    email=models.EmailField()
    password=models.CharField(max_length=10)


    # def get_absolute_url(self):
    #     return reverse('thankyou')

    def get_absolute_url(self):
        return reverse('detail',kwargs={'pk':self.pk})

ClassBased/editview/forms.py
from django import forms
from .models import Person
class ContactForm(forms.Form):
    name=forms.CharField()
    email=forms.EmailField()
    msg=forms.CharField(widget=forms.Textarea)

class PersonForm(forms.ModelForm):
    class Meta:
        model=Person
        fields=['name','email','password']
        widgets={'password':forms.PasswordInput(attrs={'class':'myclass'})}

ClassBased/editview/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import ContactForm,PersonForm
from . models import Person
from django.views.generic.edit import FormView,CreateView,UpdateView,DeleteView
from django.views.generic.base import TemplateView
from django.views.generic import DetailView, ListView
from django import forms
# Create your views here.

class ContactFormView(FormView):
    template_name='editview/contact.html'
    form_class =ContactForm
    success_url='../thankyou/'
    initial ={'name':'name'}
    def form_valid(self, form):
        # print(form)
        print(form.cleaned_data['name'])
        print(form.cleaned_data['email'])
        print(form.cleaned_data['msg'])
        # return super().form_valid(form)
        return HttpResponse('Thank You')

class ThankYouView(TemplateView):
    template_name='editview/thankyou.html'


# class PersonCreateView(CreateView):
#     model=Person
#     fields =['name','email','password']
#     success_url='../thankyou/'

#     def get_form(self):
#         form=super().get_form()
#         form.fields['password'].widget= forms.PasswordInput()
#         form.fields['name'].widget= forms.TextInput(attrs={'class':'myclass'})
#         return form

# class PersonUpdateView(UpdateView):
#     model=Person 
#     fields =['name','email','password']
#     success_url='../../thankyou/'
#     def get_form(self):
#         form=super().get_form()
#         form.fields['password'].widget= forms.PasswordInput()
#         return form
    
class PersonCreateView(CreateView):
    form_class=PersonForm
    template_name='editview/person_form.html'

class PersonUpdateView(UpdateView):
    model=Person
    form_class=PersonForm
    template_name='editview/person_form.html'

class PersonDeleteView(DeleteView):
    model=Person
    success_url='../../'
    template_name='editview/delete.html'
class PersonDetailView(DetailView):
    model=Person
class PersonListView(ListView):
    model=Person
    template_name='editview/person.html'

ClassBased/editview/templates/editview/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contact</title>
</head>
<body>
    <h3>Contact Form</h3>
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Send">
    </form>
</body>
</html>

ClassBased/editview/templates/editview/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h3>Do you want to delete {{person.name}}</h3>
    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Delete">
    </form>
    <a href="{% url 'detail' person.id %}">Cancel</a>
</body>
</html>

ClassBased/editview/templates/editview/person.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for person in person_list %}
        <li><a href="{% url 'detail' person.id%}">{{person.name}}</a></li>
    {% endfor %}
</body>
</html>

ClassBased/editview/templates/editview/person_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <table border="1px">
        <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Action</th>
        </tr>
        <tr>
            <td>{{person.name}}</td>
            <td>{{person.email}}</td>
            <td><a href="{%url 'delete' person.id %}">Delete</a></td>
        </tr>
    </table>
</body>
</html>

ClassBased/editview/templates/editview/person_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Create">
    </form>
</body>
</html>

ClassBased/editview/templates/editview/thankyou.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h3>Thank You for Contacting us</h3>
</body>
</html>